#!/usr/bin/env bash

set -e

DB_NAME=$1

if [[ -z "$DB_NAME" ]]; then
  echo "ERROR: Please provide a database name as a first parameter."
  exit 1;
fi

set -exu

DATE_FILENAME=$(date +"%d_%m_%Y__%H_%M_%S")

runuser postgres -c "cd ~/ && pg_dump -U $DB_NAME -d $DB_NAME --format=plain --serializable-deferrable --quote-all-identifiers --no-owner > \"./data/db-backup-$DATE_FILENAME.sql\""

runuser postgres -c "cd ~/ && pg_dump -U $DB_NAME -d $DB_NAME --format=plain --serializable-deferrable --quote-all-identifiers --no-owner --schema-only > \"./data/db-schema-backup-$DATE_FILENAME.sql\""
