#!/usr/bin/env bash

TMP_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$TMP_SOURCE" ]; do
  SCRIPT_PATH="$( cd -P "$( dirname "$TMP_SOURCE" )" >/dev/null 2>&1 && pwd )"
  TMP_SOURCE="$(readlink "$TMP_SOURCE")"
  [[ $TMP_SOURCE != /* ]] && TMP_SOURCE="$SCRIPT_PATH/$TMP_SOURCE"
done
SCRIPT_PATH="$( cd -P "$( dirname "$TMP_SOURCE" )" >/dev/null 2>&1 && pwd )"

export $(cat $SCRIPT_PATH/env | xargs);

export LOCAL_IP=$(ip route | grep '192.168.0.0/24' | grep -Eo '192\.168\.0\.[1-9][0-9]*');

set -exu

docker-compose -f "$SCRIPT_PATH/docker-compose.yml" -p $STACK_NAME pull

docker-compose -f "$SCRIPT_PATH/docker-compose.yml" -p $STACK_NAME down

docker-compose -f "$SCRIPT_PATH/docker-compose.yml" -p $STACK_NAME up -d
